type Subject = {
  code: string;
  title: string;
  examType: "T" | "B" | "P";
  theoryAss?: number;
  theoryFinal?: number;
  practicalAss?: number;
  practicalFinal?: number;
  total: number;
};

type SemNo = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type Semester = {
  year: number;
  semester: "Odd" | "Even";
  semNo: SemNo;
  subjects: Subject[];
  totalMarks: number;
};

export const semesters: Semester[] = [
  {
    year: 1,
    semester: "Odd",
    semNo: 1,
    totalMarks: 675,
    subjects: [
      {
        code: "ENSH_101",
        title: "Engineering Mathematics I",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT_101",
        title: "Computer Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENME_101",
        title: "Engineering Drawing",
        examType: "B",
        theoryAss: 20,
        theoryFinal: 30,
        practicalAss: 50,
        total: 100,
      },
      {
        code: "ENEX_101",
        title: "Fundamental of Electrical and Electronics Engineering",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENSH_102",
        title: "Engineering Physics",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENME_106",
        title: "Engineering Workshop",
        examType: "P",
        theoryAss: 20,
        practicalAss: 30,
        total: 50,
      },
    ],
  },
  {
    year: 1,
    semester: "Even",
    semNo: 2,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH_151",
        title: "Engineering Mathematics II",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT_151",
        title: "Object Oriented Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX_152",
        title: "Digital Logic",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX_151",
        title: "Electronic Device and Circuits",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENSH_153",
        title: "Engineering Chemistry",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENEE_154",
        title: "Electrical Circuits and Machines",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 2,
    semester: "Odd",
    semNo: 3,
    totalMarks: 775,
    subjects: [
      {
        code: "ENSH_201",
        title: "Engineering Mathematics III",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENSH_204",
        title: "Communication English",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_201",
        title: "Computer Graphics and Visualization",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_202",
        title: "Foundation of Data Science",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_203",
        title: "Theory of Computation",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENEX_201",
        title: "Microprocessors",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
    ],
  },
  {
    year: 2,
    semester: "Even",
    semNo: 4,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH_252",
        title: "Numerical Methods",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX_252",
        title: "Instrumentation",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENEX_254",
        title: "Electromagnetics",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_252",
        title: "Data Structure and Algorithm",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_253",
        title: "Data Communication",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_254",
        title: "Operating System",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 3,
    semester: "Odd",
    semNo: 5,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH_304",
        title: "Probability and Statistics",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT_301",
        title: "Database Management System",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_302",
        title: "Web Application Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_303",
        title: "Computer Organization and Architecture",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_304",
        title: "Computer Networks",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_325-344",
        title: "Elective I",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 3,
    semester: "Even",
    semNo: 6,
    totalMarks: 675,
    subjects: [
      {
        code: "ENCE_356",
        title: "Engineering Economics",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT_351",
        title: "Artificial Intelligence",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT_352",
        title: "Software Engineering",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_353",
        title: "Simulation and Modeling",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_354",
        title: "Minor Project",
        examType: "P",
        practicalAss: 50,
        total: 50,
      },
      {
        code: "ENCT_385-399",
        title: "Elective II",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 4,
    semester: "Odd",
    semNo: 7,
    totalMarks: 625,
    subjects: [
      {
        code: "ENEX_416",
        title: "Digital Signal Analysis and Processing",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_411",
        title: "Distributed and Cloud Computing",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_412",
        title: "ICT Project Management",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENEX_417",
        title: "Energy, Environment and Social Engineering",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT_435-444",
        title: "Elective III",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_413",
        title: "Project I",
        examType: "P",
        practicalAss: 50,
        total: 50,
      },
    ],
  },
  {
    year: 4,
    semester: "Even",
    semNo: 8,
    totalMarks: 550,
    subjects: [
      {
        code: "ENCT_463",
        title: "Network and Cyber Security",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_465-474",
        title: "Elective IV",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT_462",
        title: "Internship",
        examType: "P",
        practicalAss: 100,
        practicalFinal: 50,
        total: 150,
      },
      {
        code: "ENCT_461",
        title: "Project II",
        examType: "P",
        practicalAss: 100,
        practicalFinal: 50,
        total: 150,
      },
    ],
  },
];
