type Subject = {
  code: string;
  title: string;
  examType: "T" | "B" | "P";
  theoryAss?: number;
  theoryFinal?: number;
  practicalAss?: number;
  practicalFinal?: number;
  total: number;
};

type SemNo = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type Semester = {
  year: number;
  semester: "Odd" | "Even";
  semNo: SemNo;
  subjects: Subject[];
  totalMarks: number;
};

export const semesters: Semester[] = [
  {
    year: 1,
    semester: "Odd",
    semNo: 1,
    totalMarks: 675,
    subjects: [
      {
        code: "ENSH101",
        title: "Engineering Mathematics I",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT101",
        title: "Computer Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENME101",
        title: "Engineering Drawing",
        examType: "B",
        theoryAss: 20,
        theoryFinal: 30,
        practicalAss: 50,
        total: 100,
      },
      {
        code: "ENEX101",
        title: "Fundamental of Electrical and Electronics Engineering",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENSH102",
        title: "Engineering Physics",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENME106",
        title: "Engineering Workshop",
        examType: "P",
        theoryAss: 20,
        practicalAss: 30,
        total: 50,
      },
    ],
  },
  {
    year: 1,
    semester: "Even",
    semNo: 2,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH151",
        title: "Engineering Mathematics II",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT151",
        title: "Object Oriented Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX152",
        title: "Digital Logic",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX151",
        title: "Electronic Device and Circuits",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENSH153",
        title: "Engineering Chemistry",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENEE154",
        title: "Electrical Circuits and Machines",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 2,
    semester: "Odd",
    semNo: 3,
    totalMarks: 775,
    subjects: [
      {
        code: "ENSH201",
        title: "Engineering Mathematics III",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENSH204",
        title: "Communication English",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT201",
        title: "Computer Graphics and Visualization",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT202",
        title: "Foundation of Data Science",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT203",
        title: "Theory of Computation",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENEX201",
        title: "Microprocessors",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
    ],
  },
  {
    year: 2,
    semester: "Even",
    semNo: 4,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH252",
        title: "Numerical Methods",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENEX252",
        title: "Instrumentation",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENEX254",
        title: "Electromagnetics",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT252",
        title: "Data Structure and Algorithm",
        examType: "B",
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT253",
        title: "Data Communication",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT254",
        title: "Operating System",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 3,
    semester: "Odd",
    semNo: 5,
    totalMarks: 800,
    subjects: [
      {
        code: "ENSH304",
        title: "Probability and Statistics",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT301",
        title: "Database Management System",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT302",
        title: "Web Application Programming",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT303",
        title: "Computer Organization and Architecture",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT304",
        title: "Computer Networks",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT325-344",
        title: "Elective I",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 3,
    semester: "Even",
    semNo: 6,
    totalMarks: 675,
    subjects: [
      {
        code: "ENCE356",
        title: "Engineering Economics",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT351",
        title: "Artificial Intelligence",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 50,
        total: 150,
      },
      {
        code: "ENCT352",
        title: "Software Engineering",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT353",
        title: "Simulation and Modeling",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT354",
        title: "Minor Project",
        examType: "P",
        practicalAss: 50,
        total: 50,
      },
      {
        code: "ENCT385-399",
        title: "Elective II",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
    ],
  },
  {
    year: 4,
    semester: "Odd",
    semNo: 7,
    totalMarks: 625,
    subjects: [
      {
        code: "ENEX416",
        title: "Digital Signal Analysis and Processing",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT411",
        title: "Distributed and Cloud Computing",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT412",
        title: "ICT Project Management",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENEX417",
        title: "Energy, Environment and Social Engineering",
        examType: "T",
        theoryAss: 40,
        theoryFinal: 60,
        total: 100,
      },
      {
        code: "ENCT435-444",
        title: "Elective III",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT413",
        title: "Project I",
        examType: "P",
        practicalAss: 50,
        total: 50,
      },
    ],
  },
  {
    year: 4,
    semester: "Even",
    semNo: 8,
    totalMarks: 550,
    subjects: [
      {
        code: "ENCT463",
        title: "Network and Cyber Security",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT465-474",
        title: "Elective IV",
        examType: "B",
        theoryAss: 40,
        theoryFinal: 60,
        practicalAss: 25,
        total: 125,
      },
      {
        code: "ENCT462",
        title: "Internship",
        examType: "P",
        practicalAss: 100,
        practicalFinal: 50,
        total: 150,
      },
      {
        code: "ENCT461",
        title: "Project II",
        examType: "P",
        practicalAss: 100,
        practicalFinal: 50,
        total: 150,
      },
    ],
  },
];
